/**
 * This file is auto generated by cockpit-type
 */

export type Maybe<T> = T | ''

export type AssetType = {
    path: string
    title: string
    mime: string
    description?: string,
    tags?: string[],
    size: number,
    image: boolean,
    video: boolean,
    audio: boolean,
    archive: boolean,
    document: boolean,
    code: boolean,
    created: number,
    modified: number,
    _by: string,
    width: number,
    height: number,
    colors: string[],
    folder: string,
    _id: string
}

export type ImageType = {
    path: string
}

export type GalleryType = ImageType & {
    meta: {
        title: string
        asset: string
    }
}
